name: Build and test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup JDK
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17
        cache: sbt
    - name: Setup sbt
      uses: sbt/setup-sbt@v1
    - name: Setup dependencies
      run: |
        git clone --branch v0.2.0 https://github.com/phaller/spores3.git
        cd spores3
        sbt publishLocal
    - name: Build
      run: make build
    - name: Test
      run: make test
    - name: Run all examples
      run: make example-runAll
    - name: Check scalafmt
      run: make scalafmtCheck
